### C++

[参考这个链接]([C++异常处理（try catch throw）完全攻略 (biancheng.net)](http://c.biancheng.net/view/422.html))

```C++
#include <iostream>
using namespace std;

int main()
{
	int a, b, c;
	cin >> a >> b;
	try
	{
		if (b==0)
		{
			throw "divided by zero!";
		}
		c = a / b;
		cout << "c=" << c << endl;
	}
	catch (const char* msg) //这里不能写char* 也不能写string 只能写const char*
	{
		cout << msg << endl;
	}
	return 0;
}
```

当然也有`catch(...)`这样的万精油写法



### Python

```python
a = int(input('a:'))
b = int(input('b:'))
try:
    c = a / b
except ZeroDivisionError:
    print('divided by zero!')
else:
    print(c)

```

要用万金油写法可以这么写

```Python
a = int(input('a:'))
b = int(input('b:'))
try:
    c = a / b
except Exception:
    print('divided by zero!')
else:
    print(c)

```

### java

```java
package test;

import java.util.Scanner;

public class Test {
	public static void main(String[] args) {
        int a = 0, b = 0;
        try (Scanner scanner = new Scanner(System.in)) {
            a = scanner.nextInt();
            b = scanner.nextInt();
            System.out.println(a / b);
        } catch (ArithmeticException exception) {
        	System.out.println("除数为0");
        }
        System.out.print("程序结束");
    }
}
```



### 总结

看起来C++的异常处理多数是要使用者自己写的，而且throw的是值，catch的是数据类型

Python多数的异常是类，是内置的

java类似python